defaults: &defaults
  probabilities:
    default: 0.5
    max: 0.95
    min: 0.5
    deposits:
      initial: 1
  amounts:
    deposits:
      initial: 20
      creation:
        default: 10
      reaction:  
        default: 6
        comment: 6
      relationship:  
        default: 6
        add: 6
    transfers:
      reaction:
        default: 3  
        comment: 3
      relationship:
        default: 3
  percentages:  
    transfers:
      reaction:
        default: 10
        
 
development:
  <<: *defaults
 
test:
  <<: *defaults
 
production:
  <<: *defaults
