defaults: &defaults
  probabilities:
    default: 0.5
    max: 0.95
    min: 0.5
    deposits:
      initial: 1
  amounts:
    deposits:
      welcome: 2
      creation:
        default: 10
        item: 10
      reaction:  
        default: 6
        comment: 6
      relationship:  
        default: 6
        add: 6
        dm: 5
  percentages:  
    transfers:
      reaction:
        default: 10
      relationship:
        default: 10
 
development:
  <<: *defaults
 
test:
  <<: *defaults
 
production:
  <<: *defaults
