defaults: &defaults
  probabilities:
    default: 0.5
    max: 0.95
    min: 0.5
    deposits:
      initial: 1
  amounts:
    deposits:
      welcome: 20
      creation:
        default: 10
        item: 20
        guide: 10
        place: 0
      reaction:  
        default: 6
        photo: 15
        comment: 15
        bookmark: 10
        has_been: 5
        wanna_go: 5
        share: 15
        print: 15
      relationship:  
        default: 6
        add: 10
        dm: 5
  percentages:  
    transfers:
      reaction:
        default: 10
 
development:
  <<: *defaults
 
test:
  <<: *defaults
 
production:
  <<: *defaults

