defaults: &defaults
  probabilities:
    default: 0.5
    max: 0.95
    min: 0.5
    deposits:
      initial: 1
  amounts:
    deposits:
      initial: 20
      creation:
        default: 10
        place: 20
        route: 10
      reaction:  
        default: 6
        comment: 15
        bookmark: 10
        print: 15
        share: 15
        has_been: 5
        wanna_go: 5
      relationship:  
        default: 6
        add: 10
        dm: 5
    transfers:
      reaction:
        default: 3  
      relationship:
        default: 3
  percentages:  
    transfers:
      reaction:
        default: 10
 
development:
  <<: *defaults
 
test:
  <<: *defaults
 
production:
  <<: *defaults



